### ISSUE TITLE
Encapsulating different Implementation Packages for an implementation

### ISSUE THREAD

**Issue by saatkamp** [UST-QuAntiL/qc-atlas#162]
**Current Behavior:**
Current an implementation can only be linked with one executable artifact (file or URL)

**Expected Behavior:**
For a single implementation different implementation packages can be defined that package the executable artifact in a certain way, e.g. as a zip-file that can be stored, as a TOSCA Service Template located in a TOSCA repository, and many more. Thus, the handling for a certain package type can be individually defined, especially for the provisioning.
Each type defines its one logic to handle download and upload. Additionally, Provisioning Services for the different packages can be implemented. the DefaultFileImplementationPackage should only store files without additional semantics.

![image](https://user-images.githubusercontent.com/18379143/98118665-da8f5700-1eab-11eb-8ad5-96b5ccac6814.png)

**Comment by lharzenetter** [comment]
Implemented unless that the Implementation Package is not abstract yet. Maybe similar to #182
