### ISSUE TITLE
Add GETs in execution environments (size: small)

### ISSUE THREAD

**Issue by salmma** [UST-QuAntiL/qc-atlas#167]
### Acceptance Criteria

1. Add GET for 
   - /v1/cloud-services/{id}/compute-resources/{crId}
   - /v1/compute-resources/{id}/cloud-service/{csId}
   - /v1/compute-resources/{id}/compute-resource-properties/{resourceID}
   - /v1/compute-resources/{id}/software-platforms/{spId}
   - /v1/software-platforms/{id}/cloud-services/{csId}
   - /v1/software-platforms/{id}/compute-resources/{crId}

**Comment by lharzenetter** [comment]
Currently, we only need add/remove/change of the whole list
