### ISSUE TITLE
Support Concrete Solutions and Add Link from PatternAtlas to QC Atlas

### ISSUE THREAD

**Issue by salmma** [UST-QuAntiL/qc-atlas#217]
- [x] extend DB QC Atlas, add Pattern ID to Implementation table
- [x] store concrete solution (BPMN + Python files or strings) as ImplementationPackage (see QC Atlas API)
- [x] add endpoint to retrieve all concrete solutions based on Pattern ID

**Comment by salmma** [comment]
Note: endpoint with GET over all implementations (without going over algorithms) is already implemented

**Comment by salmma** [comment]
required to fulfill https://github.com/PlanQK/workflow-modeler/issues/94

**Comment by mar-be** [comment]
Current API allows uploading a file to an ImplementationPackage:
POST `{{ base_url }}/algorithms/{{ algorithmId }}/implementations/{{ implementationId }}/implementation-packages/{{ implementationPackageId }}/file`

The file can then be retrieved via:
GET `{{ base_url }}/algorithms/{{ algorithmId }}/implementations/{{ implementationId }}/implementation-packages/{{ implementationPackageId }}/file/content`
